services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./_run/minio/data:/data
    networks:
      - minilake
  
  nessie:
    image: ghcr.io/projectnessie/nessie:latest
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      NESSIE_VERSION_STORE_TYPE: JDBC
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: admin
      QUARKUS_DATASOURCE_PASSWORD: pgadmin
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/nessie
      QUARKUS_HTTP_PORT: 19120
      QUARKUS_HTTP_CORS_ENABLED: true
      QUARKUS_HTTP_CORS_ORIGINS: "*"
      QUARKUS_HTTP_CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      QUARKUS_HTTP_CORS_HEADERS: "accept,authorization,content-type,x-requested-with"
      QUARKUS_HTTP_CORS_EXPOSED_HEADERS: "Content-Disposition"
    depends_on:
      - minio
    networks:
      - minilake
  
  nessie-cli:
    image: ghcr.io/projectnessie/nessie-cli:latest
    container_name: nessie-cli
    # entrypoint: ["java", "-jar", "/app/cli/nessie-cli.jar"]
    depends_on:
      - nessie
    networks:
      - minilake
  
  nessie-restapi:
    container_name: nessie-restapi
    build:
      context: .
      tags:
        - nessie-restapi:latest
      dockerfile: nessie/restapi/Dockerfile
      args:
        - UNIQUE=$(date +%s)
    ports:
      - "19121:19121"
    depends_on:
      - nessie
    networks:
      - minilake
  
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pgadmin
      POSTGRES_DB: nessie
    ports:
      - "5432:5432"
    volumes:
      - ./_run/postgres:/var/lib/postgresql
    networks:
      - minilake
  
  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
    depends_on:
      - minio
    networks:
      - minilake

networks:
  minilake:
    driver: bridge